### ISSUE TITLE
Research Gatsby

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#198]
[Gatsby](https://www.gatsbyjs.org/) is an amazing framework and set of plugins that can be put together to make website development smoother.

Gatsby also abstracts content (Markdown, Ghost posts, etc.) from rendering, which means that we could reuse 100% of our template code. That'd mean having **only one codebase** for almost all Aragon websites, and letting that codebase consume Markdown content for the website, Ghost posts (using the [Ghost plugin](https://www.gatsbyjs.org/packages/gatsby-source-ghost/?=ghost)), etc.

**Comment by luisivan** [comment]
BTW I have used it for my personal blog and I had a great experience.

**Comment by sohkai** [comment]
### Findings

Pros:
- We can move closer towards unifying the website and the blog, but as to how much they'll share will really depend on how close they look. I'm skeptical about this as a big pro.
- Ghost doesn't support internationalization very easily, and moving to Gatsby would make this much easier to handle without gross hacks. With Gatsby we'd be able to author and keep blog content in Ghost, with various documents (for each lagnuage) associated to a single blog post that we'd fetch from Gatsby.

Cost: It'd take at least two weeks of effort to move both, as an initial estimate. The blog is the most amount of effort, as we'd have to completely rebuild it in React.

Non-items:
- It will not be much easier to edit content by moving to Gatsby. What's on Ghost will stay on Ghost, and what's on the website will stay almost exactly the same way it is now—inline text inside React components. It's really not that difficult to do copy adjustments in React, but of course layout gets more technical.
  - There are some documents that we could make easier to edit, such as the roadmap page, if we know they're going to be changing all the time
- It does not really make sense to move hack.aragon.org to Gatsby, since its project structure is meant for developers to edit anyway.

The big question then, is how much of a priority we'd make to internationalize the blog. If we're not planning to make a big push to do so, I'd put all of our resources on internationalizing the website as-is.

Internationalizing the website right now would be about the same amount of effort as internationalizing a Gatsby-version of the website.

----

### Decision

We decided that internationalization of the website should be the highest priority. We may re-evaluate a move to Gatsby on the blog when the time comes to internationalize that, or if we need major design re-syncs across aragon.org and blog.aragon.org.
