### ISSUE TITLE
Transactions activity panel

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#21]
# Idea
## User story
As as user, I want to be informed of the status of my transactions after I send them.

## Technical requirements
To let the user know the state of their transactions, we will implement an activity panel, where each item will have a progress bar and a description of the transaction being confirmed.

## Summary
By implementing an activity panel, we enable users to know what's going on, without the need of going to Etherscan or just waiting 14 seconds to have some kind of feedback,

**Comment by dizzypaty** [comment]
### Description 
For v1, the transactions activity panel will only display transactions initiated by the ‘connected’ account.

The main goal of this component is to inform the user about the status of the transactions they’ve created, and to serve as a history log of past transactions. All transactions in the activity panel can be manually dismissed except the pending ones. If the user doesn’t dismiss them, they can disappear after a set period of time.


### Behavior 
* The UI should not block when a transaction is performed.
* When possible, the UI should immediately reflect the action, before it completes.
* In case of failure or timeout, it should be possible to to retry and / or to discard it from the panel.
* We should consider an item “read” when the user closes the panel or after the interaction with the item (e.g. navigating to the originating app by clicking on the activity item)
* The button to open the panel will display a badge that indicates the number of unread items.
* Pending items are always at the top. The other items will be displayed in reverse chronological order. 
* If a pending item transforms into a confirmed / failed item while the panel is open, the information will be updated in the item itself.
* The reordering of items is done when the panel is closed.
* Pending items can not be cleared.
* It should be possible to delete items individually by clicking on the ‘x’ icon at the top right.
* **Default action:** on click of the header or content areas of the transaction item, the corresponding app that originated the action will open. 


### Anatomy 

![Anatomy.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/5b6fbca9-bda4-4aaa-a3af-05b39791dcbf)

**Header area**
* App icon (optional?)
* App name 
* App badge (if available)
* Timestamp 
	* n min(s) ago (until 59 min) and then
	* n hour(s) ago (until 23 hours) and then 
	* 1 day ago (until 1 day and 23 hours) and then
	* Actual timestamp 
	* On hover of the timestamp, we can show the complete date and time that the transaction was initiated. Format [dd/mm/yy at hh:mm]

**Content area**
* Transaction description 

**Status area**
* Icon and transaction status (pending, timed out, failed, completed) and link the word ‘transaction’ to the correspondent Etherscan page. 
	* Your transaction is pending...
	* Your transaction failed 
	* Your transaction timed out
	* Your transaction is completed
* Progress bar (if pending)
	* Right after the transaction is signed, we will show and indeterminate  progress bar until we can calculate and show an estimate. 
* Action buttons:
	* If failed, button label should be: ‘Try again’
	* If timed out, button label should be: ‘Increase gas and try again’ 

### Spacing 

![Spacing.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/faa5ce3b-0fe6-457c-81e3-4d57c39ecc41)

**Note:** We will use `8px` base grid for the spacing.

### Content guide

![Content and status variations.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/f076f6b9-7d94-4096-a1b2-8a4a7b83337a)

* Token Manager: 
	* Assign n tokens to [Address]
	* Remove n tokens [Address]
* Finance 
	* Withdrawal of [Amount]. Ref: [Reference]
	* Deposit of [Amount]. Ref: [Reference]
* Voting 
	* Vote #n: [Description]
	* Vote yes/no on #n
* Permissions 
	* On [App], grant permission to [App or address] to [Role]
	* 	On [App], revoke permission to [App or address] to [Role]
* App Center 
	* Upgrade [App name]

### Ideas for empty state

![WebApp-1366px - Emprty state 01.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/d43fa383-2ab7-48f7-bad1-8e9020668fa5)

![WebApp-1366px - Emprty state 02.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/9e3198a1-50ec-45f1-bc1b-287648614fe6)


### Examples in context

![WebApp-1366px - Transactions panel - multiple apps@2x.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/d083ff5c-f03b-4839-8b2f-fd39b5ea6317)

![WebApp-1366px - Transactions panel states.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/863f4b28-3139-4dd2-833e-5e65463908ac)

![Tablet - transactions panel open.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/87f0835c-fc14-45c5-8ca7-67b728ee27ff)

![Mobile - transactions panel open.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/22c53c99-f1f5-49e3-aa41-10d5fe731a77)

Note: The transactions panel will always have a **width of 300px** independently of the form factor.

[Figma file with assets](https://www.figma.com/file/QFgvrY5bjKzTY8XqsDmOT9du/Feedback?node-id=97%3A0)

### Kick-off meeting discussion
* These designs represent “direct” transactions.
* We need to explore how these transaction items will be represented and what content we’ll be able to fetch when a transaction is being forwarded. 
* We discussed the idea of representing **actions** instead of transactions items and showing the user the steps required to complete the forwarding path. 
* For this first iteration, we might only be able to know that the transaction is being forwarded and display this in the content area, but not knowing which app triggered it or which app will ‘execute’ the intended action.

**Comment by luisivan** [comment]
Great work @dizzypaty. This is ready to get implemented

**Comment by sohkai** [comment]
From the kickoff call for this project, some implementation roadblocks / difficulties:

- Estimating the time to mine will require an external API call, perhaps requiring authentication
- Retrying a transaction could be tricky; would need to investigate how feasible this is (usually this is better handled by the Ethereum provider itself, but then we wouldn't get information about the new transaction)
- Taking into account the full forwarding path is going to be important, as 0.7 organizations will have their default permissions set up so all actions will require a forward through both the Token Manager (checks token ownership) and Voting apps
  - For most users this will look like they're sending a transaction to the Token Manager app, when they _actually_ want to invoke something else (e.g. withdraw funds from Finance)
  - We have _at least_ knowledge about the path a transaction will take at its time of signing, so we could add this list of apps into the notification
  - We have the description of the final action the user intended at the time of signing, so this could also be included in the notification (although we should be careful: it may not actually go through, e.g. if the vote doesn't pass)
  - We _may add_ information to each app to better describe its forwarding structure so the frontend can show a more useful notification (e.g. interact with the Voting app)
- Styling the description will be tricky; we will need to investigate into how to attach better renderers to radspec

------------

**An initial implementation phase then consists of:**

- No time estimate for the transaction to be mined
- A hardcoded time to live for transactions (e.g. after ~10min of not being mined, we can assume it was lost)
- Simpler descriptions for forwarded actions (e.g. `Token Manager: forward`), and lack of styling

**The more uphill implementation items consist of, and should be scoped for future iterations:**

- Using an external API to estimate time to mine
- Attaching more detailed descriptions for forwarded actions
- Styling notification descriptions

cc @dizzypaty @luisivan

**Comment by luisivan** [comment]
I agree except for
> No time estimate for the transaction to be mined

We can use a quick and dirty Etherscan proxy or something like that

**Comment by sohkai** [comment]
Based on our sync up call today, a few notes:

- Retrying transactions is fairly complex (usually the Ethereum provider handles it, but then the client wouldn't know about this information). We will just show a timed out state without the ability to retry for now.
  - We can, however, easily detect that you've done something to manually retry or cancel a transaction (due to how account nonces work), so we can show more information in those scenarios (e.g. "this transaction was likely replaced")
- Forwarded actions are still a big sore spot, and users will definitely be confused.
  - We will likely include some vague language when a transaction has to be forwarded (e.g. "This may eventually execute ...")
  - We have at least the first and last node in the forwarding path (so the first app you're talking to, e.g. Voting, and the "target" app you'd actually like to interact with, e.g. Finance), so we could render a bit of information based on that.
- Based on how the implementation goes, we may drop the progress bar for now (imagine 5 pending transactions all with animated progress bars; it could be too busy)
