### ISSUE TITLE
Infrastructure handoff

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#227]
Complete the A1 infrastructure hand-off from Daniel.

There are a couple of high-level items that are important to understand. Let's make sure to ask directly or schedule meetings with Daniel to make sure we have them covered.

There are also a couple low-level, mechanical tasks that we should complete this week.

---------

High level:

- [x] Go through all the current documentation, understand which parts should be deprecated or updated
- [x] Understand how the secrets are currently encrypted
- [x] Understand current hosted services:
  - Rocketchat + backups
  - Matomo
- [x] Understand current Prometheus set up:
  - What is exporting information into it right now?
  - What alerts are being sent to OpsGenie?
- [x] Understand current Grafana set up
- [x] Resources and tips and tricks for operating Ethereum nodes that Daniel has learned over time; we should open source time information at some point
- [x] Understand the cloud-aspects of the [notification service](https://github.com/aragonone/notification-service)
  - Cloud build
  - Cloud postgreSQL

--------

Low level:

- [x] Update soon-expiring certificates
  - ipfs-api.eth.aragon.network 
  - ropsten.eth.aragon.network
- [ ] Upgrade matomo to latest version

**Comment by promaty** [comment]
Had to revise some advanced k8s concepts in order to proceed since you are heavily relying on stateful apps. Relationship between google load balancer -> ingress -> StatefulSets -> kube-dns is quite complicated.
I started plotting a network topology of your cluster, going from the ground up basically by inspecting what is running on the API. No way can I finish this by Friday, I reckon it will take few more weeks to go through all the intricate details and feel comfortable.

For this week I can only go through high level of general docs, secrets, rocket chat, matomo and maybe some Prometheus. Ethereum ops nuances, notification service and general maintenance tasks in the following weeks.

For low level tasks you should still ask help from @2color, I don't feel comfortable mucking about just now.

**Comment by promaty** [comment]
Today we walked through our infrastructure documentation and running k8s resources. Topics covered:

### StatefulSets
- Ethereum node storage is manually created as persistent volumes pointing to local disks. Migrations need to be performed manually using tricks such as `rsync` since google does not automatically backup local disks. And we need to use local disks because network attached storage is too slow for eth nodes to operate
- Might be worth writing a [kubernetes operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) if we want to automate the backups

### Secrets
- Most of the secrets are managed in Keybase
- Cloud KMS is used for Cloud Build because it is convenient to manage IAM permissions

### Network
- Part of the DNS is hosted in Cloudflare, part of it is Cloud DNS
- Google Firewall rules are used for additional filtering
- Traffic is exposed using Nginx ingress controller
- TLS certificates are automated using cert-manager with Letsencrypt challenge as a Cloud DNS TXT record
- Some pods are exposed using NodePort service which is required for p2p communication (but there seem to be some services which expose ports unnecessarily, need to check)
- mainnet-fast ingress is used with ws-proxy service which routes traffic to infura.io in case our local node is down (**team was experiencing some intermittent errors when running in proxy mode, needs to be investigated**)
- ropsten service is routed to infura.io but is hosted on aragon in order to have a dedicated aragon subdomain

### Monitoring
- Might be worth upgrading to kubernetes 1.14+ to get advanced Stackdriver system monitoring (no setup required, very detailed metrics for nodes and workloads)
- Honeycomb was previous monitoring solution, need to remove remaining references and system pods
- All alerts are consolidated using Prometheus operator with relevant CRDs
- Default Prometheus storage is 30 days, this might be increased in case we need more historical data
- Grafana dashboards are exported as code into repository

### Obsolete infrastructure docs
- everything related to AWS
- custom /containers, /scripts and other root files not updated for 8+ months
- Under /docs: collabora, k8s-arch, livepeer, secrets
- Under /k8s: geth-sync, util, livepeer, replica-patch
- Bitwarden and Nextcloud leave for now while still running on Exoscale

### Required doc updates
- Trivial auth service can be removed by reading secrets directly from ingress definition (needs updated manifests)
- Add some details about cert-manager and dns challenge
- Details about grafana dashboard version control
- Specify which parts of DNS are on google which on Cloudflare
- geth autoscaling not relevant, scaling is done manually
- Need more explanation on deployments service and how is it used for IPFS pinning
- Mention what is running on Exoscale
- Add documentation for Opsgenie and Statuspage setup that was done during trial week
- Revise getting started guide and main README to reflect the most recent setup

### Next steps
- Need to spend more time investigating cloud services (VPC, Firewalls and Cloud Build)
- Study cert manager in greater detail
- Familiarize myself with Prometheus Operator and Grafana setup
- Schedule another 1-2 sessions with @2color (end of November - beginning December) to cover details of Rocketchat, Matomo, notification service and general tips for operating nodes in order to finalize the handoff

**Comment by promaty** [comment]
Today we had the last handoff session focusing on individual applications:
### Rocket.Chat setup
- Deployed using official helm chart
- Configured using MongoDB
- 2 additional cron jobs are set up for backing up to persistent volume + cloud storage
### Matomo
- Custom StatefulSet deployment
- Uses MySQL as storage on Cloud SQL
- Two containers: official matomo and Cloud SQL proxy
- Missing README in infrastructure repository
### Notification service
- CI/CD is kept in a separate -ops repository and service is added as a git submodule for easier potential open sourcing
- Need to mirror private GitHub repos to Cloud Source Repositories
- Cloud Build creates docker container and applies to the cluster
- Service deployed using two containers for service and Cloud SQL proxy
- Uses PostgreSQL for storage
- 2 periodic jobs for getting blockchain details and sending emails to subscribers
- Using Knex.js for database migrations
- Emails sent using Postmark
### Grafana setup
- Uses default Prometheus operator dashboards
- Official NGINX dashboard
- Community Geth prometheus chart
- [Geth exporter](https://github.com/hunterlong/gethexporter) with a custom dashboard for lower level metrics
- Custom notification service dashboard

I now consider the handoff to be complete. We may still need to contact @2color for some specific technical details
