### ISSUE TITLE
Transparency portal fixes

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#35]
- [x] Etherscan links (on the ID column) are broken
- [x] `Human readable info` -> `Description`
- [x] All transfers appear as ANT transfer, although many of them are DAI transfers and one OMG transfer

**Comment by luisivan** [comment]
I think the DAI balances can be fixed by adding the token and its ABI

**Comment by 2color** [comment]
> Etherscan links (on the ID column) are broken

The most recent transactions have broken link because the source of truth for transaction IDs is the `transactions.json` file which is manually updated. 

I can dive deeper into this, but a first look reveals that we don't get the transaction hashes from the JSON RPC API.

The most recent version of the [gnosis wallet UI](https://wallet.gnosis.pm) doesn't seem to be any different.

So two options: 
1. Find a way to get the transaction IDs from the API
1. Ensure we don't render URLs if there's no transactionID in the transactions.json

>  All transfers appear as ANT transfer, although many of them are DAI transfers and one OMG transfer

As for all the transfers appearing as ANT, this seems to be resolved in the [upstream](https://github.com/gnosis/MultiSigWallet/blob/master/dapp/src/controllers/walletDetailCtrl.js#L251)  whereas [we have a catch all replace](https://github.com/aragon/multisig-transparency/blob/master/controllers/walletDetailCtrl.js#L291).

I will look into this tomorrow.

**Comment by 2color** [comment]
The https://github.com/aragon/multisig-transparency/pull/14 addresses everything but the etherscan URLs. 

I'm awaiting input to know if which route to solve the problem.
