### ISSUE TITLE
Clarify polls in the voting app

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#42]
[GitHub Issue](https://github.com/aragon/aragon-apps/issues/582)

- [x] Review copies
- [x] Design informative message saying that if you wanna do any binding action such as withdrawing funds or minting tokens, those don't belong in a poll
- [x] Non-binding votes shouldn't require execution: [GitHub Issue](https://github.com/aragon/aragon-apps/issues/732)

**Comment by dizzypaty** [comment]
I explored the following options: 

#### Changing the panel title to 'New Poll'
![WebApp-1366px - Poll.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/5a30ed66-47cd-4883-a927-59704105d74e)

#### Differentiating between vote types: 'Informative' and 'Binding'
![WebApp-1366px - Vote types panel 01@2x.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/85a70c99-b427-49f8-aa86-4b6f0b3aa677)

![WebApp-1366px - Vote types panel 02@2x.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/7a7073a3-2e71-4118-8363-eef2d57d62c5)

#### Renaming 'New vote' to 'New informative vote' and amending the copy in the Info component 
This is my preferred option. However, I'm still exploring the idea of **visually differentiating** informative and binding votes in the main view of the Voting app. And perhaps, allowing users to **filter by** vote types and by apps that originated them. 

![WebApp-1366px - Informative vote@2x.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/a0d330a2-5eb9-4f43-adb2-5e27ce2a8932)

[Figma file](https://www.figma.com/file/Cx2vaUgLFS6wOKvlKV0LMSnr/Voting-app-copy-(informative-VS-binding-votes))

**Comment by luisivan** [comment]
Let's go with #2 (*Differentiating between vote types: 'Informative' and 'Binding'*). Provides great contextual info when users click New vote.

**Comment by dizzypaty** [comment]
As mentioned earlier, I explored the idea of differentiating visually the informative and binding vote cards on the main view of the Voting app, and allowing users to **filter by vote type:** All, Informative or Binding. 

Also, I wanted to know what you think about using the words "Question" & "Action" instead of "Informative" & "Binging"  – cc @luisivan , @bpierre , @sohkai 

#### Labels: Informative & binging 
<img width="1366" alt="WebApp-1366px - Voting main view" src="https://user-images.githubusercontent.com/7205369/55622684-2e522f80-57a1-11e9-8e2a-79e63f48cd09.png">
<img width="1366" alt="WebApp-1366px - Voting main view-1" src="https://user-images.githubusercontent.com/7205369/55622737-5346a280-57a1-11e9-9599-ee96ad2de39e.png">

#### Labels: Question & action

<img width="1366" alt="WebApp-1366px - Voting main view-5" src="https://user-images.githubusercontent.com/7205369/55622750-5cd00a80-57a1-11e9-8da7-94a356d2bf86.png">
<img width="1366" alt="WebApp-1366px - Voting main view-3" src="https://user-images.githubusercontent.com/7205369/55622775-68bbcc80-57a1-11e9-8047-f523c8581540.png">
<img width="1366" alt="WebApp-1366px - Informative vote" src="https://user-images.githubusercontent.com/7205369/55622779-6d808080-57a1-11e9-961d-018b70bb8767.png">

**Comment by luisivan** [comment]
Question and Action feels much more human, I agree.

**Comment by bpierre** [comment]
I agree with Question / Action too. I think _Action_ specifically is less ambiguous than _Binding_: organizations might already use the term _binding vote_ to refer to their governance model (i.e. if the vote passes, individuals will respect the decision), and users might think that it is what _binding votes_ refer to. Having specific terms (Action / Question) to refer to the Aragon feature does solves this problem.

**Comment by sohkai** [comment]
From one of the Voting app's radspec strings:

> Creates a vote to execute the desired action

So yes, "Question" and "Action" do sound much better to me :). We should just make it clear that when someone votes on an "Action" that the vote _will_ do something, in a binding fashion.

---------

@dizzypaty One small note on the badge; the contrast seems a bit low (dark and dark).

The "Action / Binding" tab also looks a little bit confusing to me; at first glance it looks like it's missing input fields and buttons (looks like a bug rather than informative message telling them they can't act).

**Comment by dizzypaty** [comment]
@sohkai @bpierre I've changed the color contrast on the labels to meet WCAG AAA with small text. Also, renamed the tabs in the signer panel to 'Question' and 'Action'. 

Re the 'Action tab' looking empty, I've tried placing a 'Coming soon' message and also disabling the fields. My preference is to keep only the Info component for now, even if it's not great. Thoughts?

[Figma file](https://www.figma.com/file/Cx2vaUgLFS6wOKvlKV0LMSnr/Apps-copy-ammendements?node-id=0%3A1)

**Comment by bpierre** [comment]
> I've changed the color contrast on the labels to meet WCAG AAA with small text.

:trophy:

> Re the 'Action tab' looking empty, I've tried placing a 'Coming soon' message and also disabling the fields. My preference is to keep only the Info component for now, even if it's not great. Thoughts?

I would go for the Info-only solution as well.

**Comment by sohkai** [comment]
> I've changed the color contrast on the labels to meet WCAG AAA with small text.

⭐️ 

> My preference is to keep only the Info component for now, even if it's not great. Thoughts?

Yes, I think that makes the most sense. Perhaps we can just tweak the copy a little bit to say that you need to go to the other apps' UI to invoke those binding actions. We do have quite a bit of space to explain ourselves in that panel 😄
