### ISSUE TITLE
Upgrade all apps at once

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#44]
# Idea
## User story
As as user, I want to upgrade all my apps at once, rather than doing each separately (especially if it takes a vote per upgrade).

## Technical requirements
- Implement a single transaction to update all apps
- Implement a modal and a banner with a button for updating all apps (see https://github.com/aragon/aragon/issues/657)
- Implement a feature showcase inside a modal that describes the best features of Bella, to encourage users to upgrade

## Summary
Users will be able to update to 0.7 in just two clicks.

**Comment by luisivan** [comment]
I think the proposed solution makes sense @sohkai

**Comment by luisivan** [comment]
@dizzypaty plz add the Design step to the issue

**Comment by dizzypaty** [comment]
#### Prototype 
https://www.figma.com/proto/Bj4bhcV3ERQW72LAQE1gXfNq/Bella-0.7-Upgrade-modal?node-id=51%3A6202&scaling=contain&redirected=1

#### Figma file with assets 
https://www.figma.com/file/Bj4bhcV3ERQW72LAQE1gXfNq/Bella-0.7-Upgrade-modal?node-id=51%3A6201

#### Bella 0.7 upgrade banner 
![WebApp-1366px - Banner upgrade 0 7@2x](https://user-images.githubusercontent.com/7205369/55620465-3effa700-579b-11e9-94b5-ae2aca143fdf.jpg)

#### Bella 0.7 upgrade showcase modal
![5@2x](https://user-images.githubusercontent.com/7205369/55620539-6c4c5500-579b-11e9-85a4-2c525d7a91d3.jpg)

![5@2x](https://user-images.githubusercontent.com/7205369/55620556-75d5bd00-579b-11e9-8e8d-9a1b4094ad94.jpg)

![5@2x](https://user-images.githubusercontent.com/7205369/55620560-7a01da80-579b-11e9-8ca9-2b64a6b20e21.jpg)

![5@2x](https://user-images.githubusercontent.com/7205369/55620567-8128e880-579b-11e9-8916-94e95233cd26.jpg)

![5@2x](https://user-images.githubusercontent.com/7205369/55620577-86863300-579b-11e9-990c-0420a03fd4b9.jpg)

#### Bella 0.7 upgrade side panel 
![WebApp-1366px - Signer panel upgrade 0 13@2x(1)](https://user-images.githubusercontent.com/7205369/55620670-bc2b1c00-579b-11e9-9c96-06fa35d5cc1d.jpg)

**Comment by sohkai** [comment]
Something that came up in a discussion offline:

- Perhaps a button could also be available in the Settings / Preferences?
- Perhaps we could also add a button to the App Center?

**Comment by dizzypaty** [comment]
@sohkai , @bpierre As suggested, I've included a button to upgrade all app in the Settings app and the App Center. On click/tap, the 'Upgrade to Bella' modal will be displayed so users can go through the 0.7 features showcase. 

I will also add soon the versions for the mobile and tablet form factors!

#### My preferred options:
<img width="1368" alt="WebApp-1366px - Settings-1" src="https://user-images.githubusercontent.com/7205369/55946205-8f1fb300-5c4c-11e9-93de-e8d1966897ee.png">
<img width="1368" alt="WebApp-1366px - App-center 2" src="https://user-images.githubusercontent.com/7205369/55946215-947cfd80-5c4c-11e9-958d-39c8c9fed3e0.png">

#### Alternatively:
![WebApp-1366px - Settings 2](https://user-images.githubusercontent.com/7205369/55946542-33095e80-5c4d-11e9-85f9-ec783176d2f8.png)

<img width="1368" alt="WebApp-1366px - App-center-1" src="https://user-images.githubusercontent.com/7205369/55946246-a199ec80-5c4c-11e9-8851-85b805fa3efb.png">

[Figma file](https://www.figma.com/file/Bj4bhcV3ERQW72LAQE1gXfNq/Bella-0.7-Upgrade-modal?node-id=120%3A0)

Since we don't have _yet_ strict written rules on the use of the primary VS secondary buttons, what are your thoughts on this?

**Comment by dizzypaty** [comment]
### Mobile layouts:

<img width="375" alt="Banner" src="https://user-images.githubusercontent.com/7205369/55955032-9c469d00-5c60-11e9-8785-7feaf0d19c08.png">
<img width="375" alt="5" src="https://user-images.githubusercontent.com/7205369/55955035-9e106080-5c60-11e9-9f9c-1456d37dcef6.png">
<img width="375" alt="5" src="https://user-images.githubusercontent.com/7205369/55955039-a072ba80-5c60-11e9-9bca-98396c068e67.png">
<img width="375" alt="5" src="https://user-images.githubusercontent.com/7205369/55955041-a23c7e00-5c60-11e9-9ee8-4b4fb6c58eca.png">
<img width="375" alt="5" src="https://user-images.githubusercontent.com/7205369/55955045-a36dab00-5c60-11e9-8c23-d2612be2f88c.png">
<img width="375" alt="5" src="https://user-images.githubusercontent.com/7205369/55955053-a6689b80-5c60-11e9-958c-4c702f0a76d3.png">

### Tablet landscape and portrait layouts:
<img width="1024" alt="Modal TL" src="https://user-images.githubusercontent.com/7205369/55955061-aa94b900-5c60-11e9-9a0a-3ffdffc1a5a9.png">
<img width="660" alt="Modal TP" src="https://user-images.githubusercontent.com/7205369/55955064-ac5e7c80-5c60-11e9-897c-b3048743ff9e.png">

[Figma file](https://www.figma.com/file/Bj4bhcV3ERQW72LAQE1gXfNq/Bella-0.7-Upgrade-modal?node-id=51%3A6201)
